version: "3"
services:
  memcached:
    image: memcached:alpine
    command:
      - "memcached"
      - "-v"
      - "-B"
      - "binary"
    ports:
      - "11211-11213:11211"
  toxiproxy:
    image: shopify/toxiproxy
    ports:
      - "8474:8474"
      - "21211:21211"
  resiliency:
    image: memcached:alpine
    command:
      - "memcached"
      - "-v"
      - "-B"
      - "binary"
